# setup/config.yaml

system:
  require_gpu: true
  gpu_check_cmd: "nvidia-smi"
  trtexec_cmd: "trtexec"
  trtexec_timeout_sec: 900

paths:
  repo_dir: "/workspace/live_cam_changer"
  models_dir: "/workspace/models"
  onnx_dir: "/workspace/models/onnx"
  trt_dir: "/workspace/models/tensorrt"

actions:
  verify_trtexec: true
  run_clone_repo: false        # false because your repo is already cloned
  run_download_models: true
  run_convert_trt: true

models:
  - name: "inswapper"
    type: "onnx"
    url: "https://huggingface.co/hacksider/deep-live-cam/resolve/main/inswapper_128_fp16.onnx?download=true"
    filename: "inswapper_128_fp16.onnx"
    convert_to_trt: true
    trt_filename: "inswapper_128_fp16.trt"
    trtexec_args: "--fp16 --workspace=2048"
